#! /bin/sh
for i in CHG CHGCAR WAVECAR DOSCAR EIGENVAL OSZICAR PCDAT vasprun.xml slurm-* vasp-gamma *.gjf *.vasp *.pos *.xyz
do
    for j in `find ./ -name $i`
    do
        echo "$j"
        rm $j
    done
done
