#!/bin/bash
if [ "$#" -eq "2" ];then
    energy $@
    energy $@ |sed -n '/energy/p' |awk 'BEGIN{count=0;} {a[count]=$4;count++;} END{print a[1]-a[0]}'
else
    echo "number of parameters is wrong"
fi
