#!/bin/bash
echo ""
if [ -e OUTCAR ]
then
    grep "energy  with" OUTCAR |tail -1
elif [ "$1" != "" ]
then
    for i in $@
    do
        for j in `find $i -name OUTCAR |sort`
        do
            echo "$j"
            grep "energy  with" $j |tail -1
        done
    done
else
    for i in `find ./ -name OUTCAR |sort`
    do
        echo "$i"
        grep "energy  with" $i |tail -1
    done
fi
echo ""
